"""Postgres schema for Codex session ingestion tables.

Purpose: Postgres schema definition matching the SQLite layout.
Author: Codex with Lauren Parlett
Date: 2025-11-24
Related tests: tests/test_cli_scripts.py, tests/test_redactions.py
AI-assisted: Codex (GPT-5)
"""

# pylint: disable=duplicate-code

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path TEXT NOT NULL UNIQUE,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER NOT NULL UNIQUE REFERENCES files(id) ON DELETE CASCADE,
    session_id TEXT,
    session_timestamp TEXT,
    raw_json TEXT
);

CREATE TABLE IF NOT EXISTS session_context (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL UNIQUE REFERENCES sessions(id) ON DELETE CASCADE,
    cwd TEXT,
    approval_policy TEXT,
    sandbox_mode TEXT,
    network_access TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prompts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    prompt_index INTEGER NOT NULL,
    timestamp TEXT,
    message TEXT,
    active_file TEXT,
    open_tabs TEXT,
    my_request TEXT,
    raw_json TEXT
);

CREATE TABLE IF NOT EXISTS redaction_rules (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('regex', 'marker', 'literal')),
    pattern TEXT NOT NULL,
    scope TEXT NOT NULL DEFAULT 'prompt'
        CHECK (scope IN ('prompt', 'field', 'global')),
    replacement_text TEXT NOT NULL,
    rule_fingerprint TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    reason TEXT,
    actor TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS redactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER REFERENCES files(id) ON DELETE CASCADE,
    prompt_id INTEGER REFERENCES prompts(id) ON DELETE CASCADE,
    rule_id TEXT REFERENCES redaction_rules(id) ON DELETE SET NULL,
    rule_fingerprint TEXT NOT NULL,
    field_path TEXT,
    reason TEXT,
    actor TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    session_file_path TEXT,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_redactions_prompt
    ON redactions(prompt_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_redactions_application
    ON redactions(
        file_id,
        prompt_id,
        field_path,
        rule_id,
        rule_fingerprint
    );

CREATE TABLE IF NOT EXISTS token_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_id INTEGER NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
    timestamp TEXT,
    primary_used_percent REAL,
    primary_window_minutes INTEGER,
    primary_resets TEXT,
    secondary_used_percent REAL,
    secondary_window_minutes INTEGER,
    secondary_resets TEXT,
    raw_json TEXT
);

CREATE TABLE IF NOT EXISTS turn_context_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_id INTEGER NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
    timestamp TEXT,
    writable_roots TEXT,
    raw_json TEXT
);

CREATE TABLE IF NOT EXISTS agent_reasoning_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_id INTEGER NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
    timestamp TEXT,
    source TEXT,
    text TEXT,
    raw_json TEXT
);

CREATE TABLE IF NOT EXISTS function_plan_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_id INTEGER NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
    timestamp TEXT,
    name TEXT,
    arguments TEXT,
    raw_json TEXT
);

CREATE TABLE IF NOT EXISTS function_calls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_id INTEGER NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
    call_timestamp TEXT,
    output_timestamp TEXT,
    name TEXT,
    call_id TEXT,
    arguments TEXT,
    output TEXT,
    raw_call_json TEXT,
    raw_output_json TEXT
);

CREATE TABLE IF NOT EXISTS events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    timestamp TEXT NOT NULL,
    event_type TEXT NOT NULL,
    category TEXT NOT NULL,
    priority TEXT NOT NULL,
    session_id TEXT,
    data TEXT,
    raw_json TEXT
);
"""

TABLES_IN_COPY_ORDER: tuple[str, ...] = (
    "files",
    "sessions",
    "session_context",
    "prompts",
    "redactions",
    "token_messages",
    "turn_context_messages",
    "agent_reasoning_messages",
    "function_plan_messages",
    "function_calls",
    "events",
)
